name: AnyRealm Genevn Kernel Build
# Source repo: https://github.com/015stray91/kernel-msm-1.git
# Toolchain: https://github.com/015stray91/android-kernel-tools.git

on:
  workflow_dispatch:
    inputs:
      device_codename:
        description: "Device codename"
        type: choice
        options:
          - parrot
          - genevn
        default: "genevn"
      add_susfs:
        description: "Add SUSFS"
        type: boolean
        default: true
      add_zeromount:
        description: "Add ZeroMount"
        type: boolean
        default: true
      add_overlayfs:
        description: "Add OverlayFS"
        type: boolean
        default: true
      add_zram:
        description: "Add ZRAM"
        type: boolean
        default: true
      add_kpm:
        description: "Add KPM"
        type: boolean
        default: true

jobs:
  build:
    uses: ./.github/workflows/Genevn-build.yml
    secrets: inherit
    with:
      device_codename: ${{ inputs.device_codename }}
      add_susfs: ${{ inputs.add_susfs }}
      add_zeromount: ${{ inputs.add_zeromount }}
      add_overlayfs: ${{ inputs.add_overlayfs }}
      add_zram: ${{ inputs.add_zram }}
      add_kpm: ${{ inputs.add_kpm }}
